export const mandate = {
  id: "demo-mandate-001",
  capitalUsd: 10_000,
  reserveFloorUsd: 3_000,
  minimumNetApyPercent: 8,
  maximumStressLossPercent: 7,
  maximumPoolAllocationPercent: 50,
  minimumPoolTvlUsd: 1_000_000,
  minimumPoolAgeDays: 30,
  approvedAssets: ["USDC", "WETH"],
  approvedProtocols: ["Uniswap v3"],
  priceShocksPercent: [-30, -20, 20, 30],
  volatilityPenaltyFactor: 0.08,
  maximumDataAgeMinutes: 1_440,
  maximumPriceDisagreementPercent: 2,
  maximumDailyTvlChangePercent: 40,
  maximumPlausibleFeeApyPercent: 100,
};

export const candidatePools = [
  {
    protocol: "Uniswap v3",
    pair: "USDC/WETH 0.05%",
    assets: ["USDC", "WETH"],
    grossApyPercent: 19,
    annualizedVolatilityPercent: 38,
    annualGasCostUsd: 35,
    tvlUsd: 18_000_000,
    ageDays: 500,
    riskyAssetWeight: 1,
  },
  {
    protocol: "Uniswap v3",
    pair: "USDC/WETH 0.30%",
    assets: ["USDC", "WETH"],
    grossApyPercent: 16,
    annualizedVolatilityPercent: 30,
    annualGasCostUsd: 35,
    tvlUsd: 25_000_000,
    ageDays: 600,
    riskyAssetWeight: 0.75,
  },
  {
    protocol: "Uniswap v3",
    pair: "USDC/WETH BOOSTED",
    assets: ["USDC", "WETH"],
    grossApyPercent: 61,
    annualizedVolatilityPercent: 115,
    annualGasCostUsd: 55,
    tvlUsd: 650_000,
    ageDays: 4,
    riskyAssetWeight: 1.6,
  },
];
